### PR TITLE
Only add a watch when there is a template url.

### PR DESCRIPTION
**Pull request by justincohan**
The watches can get expensive so this helps limit them to only when needed.

### CODE REVIEW

**Comment by boneskull** [comment]
@justincohan sorry missed this.  I don't think we can do this safely, because the `title` attribute can be interpolated, right?

**Comment by justincohan** [comment]
You're probably tight but If title is changed wouldn't the observe function fire again causing the bindings to be updated?

**Comment by boneskull** [comment]
@justincohan dunno.  can you test it with an interpolated `title` attribute and see if changing the value still works?

**Comment by justincohan** [comment]
@boneskull It looks like an interpolated title doesn't work with this code as it is.  From what it seems the tooltip is only created if one doesn't exist.  If one does exist the existing one doesn't get updated and the new title value is shown as the default browser tooltip.

**Pull request closed without merging**
